"""Add time_cost to Task

Revision ID: 1dbef96b8352
Revises: 1a8440d3eaad
Create Date: 2015-02-10 12:43:51.881434

"""

# revision identifiers, used by Alembic.
revision = '1dbef96b8352'
down_revision = '1a8440d3eaad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_cost', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.drop_column('time_cost')
    ### end Alembic commands ###
