"""add constraint in manager table

Revision ID: 25f0840c5d87
Revises: 593c59c4c834
Create Date: 2015-01-20 16:05:15.460375

"""

# revision identifiers, used by Alembic.
revision = '25f0840c5d87'
down_revision = '593c59c4c834'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.create_unique_constraint('connection_uix', ['ip_address', 'port'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_constraint('connection_uix')

    ### end Alembic commands ###
