"""Add child to Task

Revision ID: 2c82132f2ae3
Revises: 4bbcb4d706ef
Create Date: 2015-02-09 18:09:35.133774

"""

# revision identifiers, used by Alembic.
revision = '2c82132f2ae3'
down_revision = '4bbcb4d706ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.drop_column('child_id')
    ### end Alembic commands ###
