"""output path

Revision ID: 1068cdc2fd76
Revises: 2c4b6eae4733
Create Date: 2015-01-07 13:27:14.653646

"""

# revision identifiers, used by Alembic.
revision = '1068cdc2fd76'
down_revision = '2c4b6eae4733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_path_linux', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output_path_osx', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output_path_win', sa.Text(), nullable=True))
        batch_op.drop_column('output')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('output_path_win')
        batch_op.drop_column('output_path_osx')
        batch_op.drop_column('output_path_linux')

    ### end Alembic commands ###
