"""Add last_activity to Workers

Revision ID: 4192333f8372
Revises: 4ab0a557a2ea
Create Date: 2015-03-14 17:01:42.541357

"""

# revision identifiers, used by Alembic.
revision = '4192333f8372'
down_revision = '4ab0a557a2ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('last_activity')

    ### end Alembic commands ###
