"""Add nimby to Workers

Revision ID: 538d0476a60f
Revises: bb419a4193b
Create Date: 2015-02-16 14:46:07.217234

"""

# revision identifiers, used by Alembic.
revision = '538d0476a60f'
down_revision = 'bb419a4193b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nimby', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('nimby')

    ### end Alembic commands ###
