"""Manager logo

Revision ID: 10bfa3934fd7
Revises: 3a2606d017ea
Create Date: 2015-05-29 15:44:37.755134

"""

# revision identifiers, used by Alembic.
revision = '10bfa3934fd7'
down_revision = '3a2606d017ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('logo', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='unique')
    ### end Alembic commands ###
