"""Add parser to Task

Revision ID: 1a8440d3eaad
Revises: 2c82132f2ae3
Create Date: 2015-02-10 11:41:52.667592

"""

# revision identifiers, used by Alembic.
revision = '1a8440d3eaad'
down_revision = '2c82132f2ae3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parser', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.drop_column('parser')
    ### end Alembic commands ###
