"""render path

Revision ID: 1fa7caa8a01f
Revises: 3fc5f3e23c05
Create Date: 2015-01-07 12:56:39.843934

"""

# revision identifiers, used by Alembic.
revision = '1fa7caa8a01f'
down_revision = '3fc5f3e23c05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('render_path_linux', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('render_path_osx', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('render_path_server', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('render_path_win', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('render_path_win')
        batch_op.drop_column('render_path_server')
        batch_op.drop_column('render_path_osx')
        batch_op.drop_column('render_path_linux')

    ### end Alembic commands ###
