"""Adding last_activity to tasks

Revision ID: 2d33ab39d177
Revises: acabe34eef9
Create Date: 2015-03-21 19:25:57.609845

"""

# revision identifiers, used by Alembic.
revision = '2d33ab39d177'
down_revision = 'acabe34eef9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'task', schema=None) as batch_op:
        batch_op.drop_column('last_activity')
    ### end Alembic commands ###
