"""Manager table cleanup

Revision ID: 304eee7d9def
Revises: 86dad093873
Create Date: 2015-10-19 01:20:39.988644

"""

# revision identifiers, used by Alembic.
revision = '304eee7d9def'
down_revision = '86dad093873'

from alembic import op
import sqlalchemy as sa


def upgrade():
    with op.batch_alter_table('manager') as batch_op:
        batch_op.add_column(sa.Column('host', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('token_expires', sa.DateTime(), nullable=True))
        batch_op.drop_column('uuid')
        batch_op.drop_column('port')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('port', sa.INTEGER(), nullable=True))
    op.add_column('manager', sa.Column('uuid', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('manager', 'token_expires')
    op.drop_column('manager', 'token')
    op.drop_column('manager', 'host')
    ### end Alembic commands ###
