"""running_tasks column

Revision ID: 333fa88f21fa
Revises: 3e29792080f3
Create Date: 2015-01-19 18:33:53.044344

"""

# revision identifiers, used by Alembic.
revision = '333fa88f21fa'
down_revision = '3e29792080f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('running_tasks', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_column('running_tasks')

    ### end Alembic commands ###
