"""Removing tasks_count tasks_completed

Revision ID: 3a2606d017ea
Revises: 4bb5c8ca790e
Create Date: 2015-05-26 09:42:43.830213

"""

# revision identifiers, used by Alembic.
revision = '3a2606d017ea'
down_revision = '4bb5c8ca790e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('tasks_status', sa.String(256), nullable=True))
    op.drop_column('job', 'tasks_count')
    op.drop_column('job', 'tasks_completed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('tasks_completed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('tasks_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('job', 'tasks_status')
    ### end Alembic commands ###
