"""rename job_managers

Revision ID: 3e29792080f3
Revises: 376650d684d7
Create Date: 2015-01-19 12:04:10.391350

"""

# revision identifiers, used by Alembic.
revision = '3e29792080f3'
down_revision = '376650d684d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('relation_job_manager')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_job_manager',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], [u'job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_managers')
    ### end Alembic commands ###
