"""Edit time for jobs

Revision ID: 474c8055a404
Revises: 10bfa3934fd7
Create Date: 2015-06-03 19:44:35.875406

"""

# revision identifiers, used by Alembic.
revision = '474c8055a404'
down_revision = '10bfa3934fd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('date_edit', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'date_edit')
    ### end Alembic commands ###
