"""Adding tasks_count tasks_completed

Revision ID: 4bb5c8ca790e
Revises: 111a89ae6a55
Create Date: 2015-05-26 09:01:35.025857

"""

# revision identifiers, used by Alembic.
revision = '4bb5c8ca790e'
down_revision = '111a89ae6a55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('tasks_completed', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('tasks_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'tasks_count')
    op.drop_column('job', 'tasks_completed')
    ### end Alembic commands ###
