"""empty message

Revision ID: 593c59c4c834
Revises: 333fa88f21fa
Create Date: 2015-01-20 12:23:27.594460

"""

# revision identifiers, used by Alembic.
revision = '593c59c4c834'
down_revision = '333fa88f21fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.alter_column('running_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.alter_column('running_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)

    ### end Alembic commands ###
