"""job creation datetime

Revision ID: acabe34eef9
Revises: 1dbef96b8352
Create Date: 2015-02-27 17:35:38.332405

"""

# revision identifiers, used by Alembic.
revision = 'acabe34eef9'
down_revision = '1dbef96b8352'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    ### end Alembic commands ###
