"""Job Types and workers association

Revision ID: 13b29170cfb3
Revises: 4192333f8372
Create Date: 2015-06-07 22:00:26.155352

"""

# revision identifiers, used by Alembic.
revision = '13b29170cfb3'
down_revision = '4192333f8372'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_job_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('job_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id', 'worker_id', 'job_type_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_job_type')
    op.drop_table('job_type')
    ### end Alembic commands ###
