"""add activity column

Revision ID: 5211eba1d83f
Revises: 512e5da2ebde
Create Date: 2015-02-03 18:09:43.875633

"""

# revision identifiers, used by Alembic.
revision = '5211eba1d83f'
down_revision = '512e5da2ebde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.String(64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('activity')
    ### end Alembic commands ###
