"""add current task to workers

Revision ID: 512e5da2ebde
Revises: b1553a4fb07
Create Date: 2015-01-28 11:10:45.659234

"""

# revision identifiers, used by Alembic.
revision = '512e5da2ebde'
down_revision = 'b1553a4fb07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('current_task')
    ### end Alembic commands ###