"""Removed Tasks

Revision ID: 556e494b5f75
Revises: 5211eba1d83f
Create Date: 2015-02-06 21:28:41.699563

"""

# revision identifiers, used by Alembic.
revision = '556e494b5f75'
down_revision = '5211eba1d83f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_type')
    op.drop_table('task')
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('log')

    op.create_table('task',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('worker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('frame_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('frame_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('frame_current', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('format', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('file_path_linux', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('file_path_win', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('file_path_osx', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('settings', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('output_path_linux', mysql.TEXT(), nullable=True),
    sa.Column('output_path_osx', mysql.TEXT(), nullable=True),
    sa.Column('output_path_win', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('task_type',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('pre_command', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('post_command', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
